/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// gesture
// This file was @generated by ai8xize.py --verbose --test-dir /home/max78000/max78000-auth/synthesis/gesture --prefix gesture --checkpoint-file /home/max78000/max78000-auth/training/checkpoints/gesture64_final.pth.tar --config-file networks/gesture64.yaml --device MAX78000 --compact-data --mexpress --timer 0 --display-checkpoint

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 3-channel 64x64 data input (12288 bytes total / 4096 bytes per channel):
// CHW 64x64, channel 0
static const uint32_t input_0[] = SAMPLE_INPUT_0;

// CHW 64x64, channel 1
static const uint32_t input_16[] = SAMPLE_INPUT_16;

// CHW 64x64, channel 2
static const uint32_t input_32[] = SAMPLE_INPUT_32;

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  memcpy32((uint32_t *) 0x50400000, input_0, 1024);
  memcpy32((uint32_t *) 0x50800000, input_16, 1024);
  memcpy32((uint32_t *) 0x50c00000, input_32, 1024);
}

// Expected output of layer 13 (conv14_Conv_4) for gesture given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

static int32_t ml_data[CNN_NUM_OUTPUTS];

int main(void)
{
  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test gesture ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  load_input(); // Load data input
  cnn_start(); // Start CNN processing

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN

  if (check_output() != CNN_OK) fail();
  cnn_unload((uint32_t *) ml_data);

  printf("\n*** PASS ***\n\n");

#ifdef CNN_INFERENCE_TIMER
  printf("Approximate inference time: %u us\n\n", cnn_time);
#endif

  cnn_disable(); // Shut down CNN clock, disable peripheral


  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 76,158,976 ops (75,573,248 macc; 585,728 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0 (conv1_Conv_10): 1,835,008 ops (1,769,472 macc; 65,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1 (conv2_Conv_8): 11,878,400 ops (11,796,480 macc; 81,920 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2 (conv3_Conv_8): 14,827,520 ops (14,745,600 macc; 81,920 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3 (conv4_Conv_8): 14,827,520 ops (14,745,600 macc; 81,920 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4 (conv5_Conv_8): 3,788,800 ops (3,686,400 macc; 102,400 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5 (conv6_Conv_8): 3,706,880 ops (3,686,400 macc; 20,480 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6 (conv7_Conv_8): 8,155,136 ops (8,110,080 macc; 45,056 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7 (conv8_Conv_8): 4,923,392 ops (4,866,048 macc; 57,344 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8 (conv9_Conv_8): 5,320,704 ops (5,308,416 macc; 12,288 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9 (conv10_Conv_8): 2,672,640 ops (2,654,208 macc; 18,432 comp; 0 add; 0 mul; 0 bitwise)
    Layer 10 (conv11_Conv_8): 800,768 ops (786,432 macc; 14,336 comp; 0 add; 0 mul; 0 bitwise)
    Layer 11 (conv12_Conv_8): 1,050,624 ops (1,048,576 macc; 2,048 comp; 0 add; 0 mul; 0 bitwise)
    Layer 12 (conv13_Conv_8): 2,361,344 ops (2,359,296 macc; 2,048 comp; 0 add; 0 mul; 0 bitwise)
    Layer 13 (conv14_Conv_4): 10,240 ops (10,240 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 369,632 bytes out of 442,368 bytes total (83.6%)
  Bias memory:   1,125 bytes out of 2,048 bytes total (54.9%)
*/

