/* Auto-generated by db_gen/manage_db.py — do not edit */

#define DB_NUM_ENTRIES   1
#define DB_EMBEDDING_DIM 64

#define DB_SPEAKER_NAMES { "Jisoo" }

#define DB_EMBEDDINGS { \
  /* Jisoo  */ { -4, -15, 11, -15, -12, 9, 29, -10, -31, -16, -17, -13, 11, -8, -6, -1, -6, 21, 24, 1, -3, -21, -31, -24, -10, 15, -15, 14, 6, 9, -7, -12, -3, 21, -18, 17, -13, -20, -14, -3, -21, -2, 3, -14, -13, -7, -17, -26, -6, 28, 13, -1, 21, 6, -2, -21, -7, 11, -10, -25, -35, 19, -8, 21 } \
}
