/* Auto-generated by db_gen/manage_db.py — do not edit */

#define DB_NUM_ENTRIES   1
#define DB_EMBEDDING_DIM 64

#define DB_SPEAKER_NAMES { "Js" }

#define DB_EMBEDDINGS { \
  /* Js     */ { 1, 6, 25, -14, -11, 9, 30, -14, -12, -18, -1, -12, 20, -15, -12, 8, 2, 11, 17, -14, -13, -25, -27, -19, 4, 18, -49, 12, 23, 7, -19, -6, 0, 7, -14, 8, -5, -16, -18, -4, -14, 0, -12, -10, 14, 14, -5, -5, -16, 9, 16, -1, 15, 7, -7, -2, -3, 18, -2, -32, -40, 10, -2, 27 } \
}
